# Generated by Django 3.1.5 on 2021-02-09 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('field_type', models.CharField(choices=[('LB', 'Label'), ('ST', 'Sticker'), ('MX', 'Mixed')], default='LB', max_length=32)),
                ('label', models.CharField(max_length=256)),
                ('positionX', models.IntegerField()),
                ('positionY', models.IntegerField()),
                ('rowspan', models.IntegerField(default=1)),
                ('colspan', models.IntegerField(default=1)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.field')),
            ],
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sizeX', models.IntegerField()),
                ('sizeY', models.IntegerField()),
                ('privacy_type', models.CharField(choices=[('PV', 'Private'), ('PB', 'Public')], default='PV', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('height', models.TextField()),
                ('width', models.TextField()),
                ('bgcolor', models.CharField(max_length=9)),
                ('txtcolor', models.CharField(max_length=7)),
                ('fontsize', models.TextField()),
                ('border', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('EP', 'Epics'), ('ST', 'Stories'), ('OT', 'Other')], default='EP', max_length=32)),
                ('content', models.TextField(default='')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.field')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.style')),
            ],
        ),
        migrations.AddField(
            model_name='field',
            name='sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sheet'),
        ),
        migrations.AddField(
            model_name='field',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.style'),
        ),
    ]
