# Generated by Django 3.1.5 on 2021-01-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('field_type', models.CharField(choices=[('LB', 'Label'), ('ST', 'Sticker'), ('MX', 'Mixed')], default='LB', max_length=32)),
                ('label', models.CharField(max_length=256)),
                ('positionX', models.IntegerField()),
                ('positionY', models.IntegerField()),
                ('rowspan', models.IntegerField(default=1)),
                ('colspan', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('EP', 'Epics'), ('ST', 'Stories'), ('OT', 'Other')], default='EP', max_length=32)),
                ('content', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sizeX', models.IntegerField()),
                ('sizeY', models.IntegerField()),
                ('privacy_type', models.CharField(choices=[('PV', 'Private'), ('PB', 'Public')], default='PV', max_length=32)),
            ],
        ),
    ]
