# Generated by Django 3.1.5 on 2021-02-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_field_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.TextField()),
                ('width', models.TextField()),
                ('bgcolor', models.CharField(max_length=8)),
                ('txtcolor', models.CharField(max_length=6)),
                ('fontsize', models.TextField()),
                ('border', models.TextField()),
            ],
        ),
    ]
