# Generated by Django 3.1.5 on 2021-02-03 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='style',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='table.style'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='style',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='table.style'),
            preserve_default=False,
        ),
    ]
