# Generated by Django 3.1.5 on 2021-02-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0005_auto_20210203_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='name',
            field=models.CharField(default='Style1', max_length=30),
            preserve_default=False,
        ),
    ]
